In [2]:
print(123)

123


# 一、ndarray
## 1.ndarray的特性
### 多维性

In [3]:
import numpy as np

In [4]:
arr = np.array(5)               #创建0维的ndarray数组
print(arr)
print("arr的维度：", arr.ndim)    # number of dimensions

5
arr的维度： 0


In [5]:
arr = np.array([1,2,3])        #创建1维的ndarray数组
print(arr)
print("arr的维度：", arr.ndim)    # number of dimensions

[1 2 3]
arr的维度： 1


In [6]:
arr = np.array([[1,2,2],[4,5,3],[7,8,9],[2,2,2]])       #创建2维的ndarray数组
print(arr)
print("arr的维度：", arr.ndim)           # number of dimensions

[[1 2 2]
 [4 5 3]
 [7 8 9]
 [2 2 2]]
arr的维度： 2


In [7]:
arr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])       #创建多维的ndarray数组
print(arr)
print("arr的维度：", arr.ndim)           # number of dimensions

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr的维度： 3


### 同质性

In [8]:
arr = np.array(['abc',1])       #不同数据类型会被转换成相同数据类型
print(arr)

['abc' '1']


### 高效性

## 2.ndarray的属性

In [9]:
arr = np.array(1)
print(arr)
print('数组的形状：', arr.shape)

1
数组的形状： ()


In [10]:
arr = np.array([1,2,3])
print(arr)
print('数组的形状：', arr.shape)

[1 2 3]
数组的形状： (3,)


In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状：', arr.shape)
print('数组的维度：',arr.ndim)
print('元素的个数：',arr.size)
print('元素的数据类型：',arr.dtype)
print('元素的转置\n', arr.T)

[[1 2 3]
 [4 5 6]]
数组的形状： (2, 3)
数组的维度： 2
元素的个数： 6
元素的数据类型： int64
元素的转置
 [[1 4]
 [2 5]
 [3 6]]


### 3.ndarray的创建

In [12]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr = np.array([list1,list2,list3] , dtype = np.float64)
print(arr)
print('数组的维度：',arr.ndim)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
数组的维度： 2


In [13]:
#copy
arr1 = np.copy(arr) # arr1元素跟arr相同，但是 是两个数组
print(arr1)
arr1[1] = [9,8,7] #[0][1][2][:1][:2][0:2]
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [9. 8. 7.]
 [7. 8. 9.]]


In [14]:
# 预定义形状
# 全0 全1 未初始化 固定值
arr = np.zeros((2,3))
print(arr)
arr1 = np.zeros(10,dtype=int)
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[0 0 0 0 0 0 0 0 0 0]


In [15]:
#全1
arr2 = np.ones(2,dtype=int)
print(arr2)

[1 1]


In [16]:
#未初始化
arr3 = np.empty((2,2))
print(arr3)

[[2.12199579e-314 7.74528464e-312]
 [5.49400998e-321 7.74528464e-312]]


In [17]:
arr4 = np.full((2,2),555)
print(arr4)

[[555 555]
 [555 555]]


In [18]:
barr = np.zeros_like(arr)
print(barr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# 等差数列——固定值
arr = np.arange(1,10,2)  # start , end , step
print(arr)

[1 3 5 7 9]


In [20]:
# 等间隔数列
arr = np.linspace(1,10,4,dtype=int) # start , end , num(num-1个间隔)
print(arr)

arr = np.arange(1,11,3,dtype=int)  # start , end , step
print(arr)

[ 1  4  7 10]
[ 1  4  7 10]


In [21]:
# 对数间隔数列
arr = np.logspace(0,4,3,base=2,dtype=int)
print(arr)

[ 1  4 16]


![image.png](./2.jpg)

In [22]:
# 特殊矩阵
#单位矩阵：主对角线上数字为1，其他数字为0
arr = np.eye(3,4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [23]:
#对角矩阵： 主对角线非零，其他数字为0
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [24]:
#随机数的生成
#生成0-1间的随机浮点数，均匀分布
arr = np.random.randn(3,4)
print(arr)

[[-0.26028642  1.97083981  0.6733975  -1.77874598]
 [-0.14349741 -0.53486037 -0.25481586  1.22061769]
 [-0.55875218 -1.11869647 -0.92207599  1.41489443]]


In [25]:
#生成指定区间的随机浮点数
arr = np.random.uniform(0,4,(2,3))   #0,4:区间 ， （2，3）：形状
print(arr)

[[2.19318373 1.04096798 2.57541581]
 [3.75329105 2.18044284 3.38447169]]


In [26]:
#生成指定区间的随机整数
arr = np.random.randint(0,30,(2,3))
print(arr)

[[27 14 26]
 [13  2 25]]


In [27]:
#生成随机数列（正态分布）
arr = np.random.randn(2,3)
print(arr)

[[-0.3688653   0.43438271 -0.15777797]
 [-0.36496206 -1.53092137  0.96100708]]


In [28]:
#设置随机种子
np.random.seed(1)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[6 9 6 1 1]
 [2 8 7 3 5]]


### 4.ndarray的数据类型
#### 布尔 bool
#### 整数 int uint
#### 浮点数 float
#### 复数 complex

In [29]:
arr = np.array([1,0,3,0],dtype='bool')
print(arr)
arr = np.array([1,0,3,0],dtype=np.bool)
print(arr)
arr = np.array([1,0,3,0],dtype=np.int8) #int8:取值范围-128--127
print(arr)

[ True False  True False]
[ True False  True False]
[1 0 3 0]


In [30]:
### 5.索引与切片

In [31]:
arr = np.random.randint(0,30,10)
print(arr)
print(arr[:])   #索引所有元素
print(arr[0:3])
print(arr[slice(0,5,2)]) #start,end,step
print(arr[:2])  #索引数：[a:b] ---> [第a个元素开始:第b-1个元素结束]
print(arr[(arr>10) & (arr<19)  ]) #布尔索引

[ 5 18 20 11 28 10 28 29 14 18]
[ 5 18 20 11 28 10 28 29 14 18]
[ 5 18 20]
[ 5 20 28]
[ 5 18]
[18 11 14 18]


In [32]:
arr = np.random.randint(0,30,(3,4))
print(arr)

[[ 4 23 23  9]
 [17 23  0 22]
 [13  9  9  7]]


In [33]:
print(arr[2,1])
print(arr[:,:])

9
[[ 4 23 23  9]
 [17 23  0 22]
 [13  9  9  7]]


In [34]:
print(arr[0,:])  #第0行
print(arr[:,0])  #第0列

[ 4 23 23  9]
[ 4 17 13]


In [35]:
print(arr[0,2:4])

[23  9]


In [36]:
print(arr[2])
print(arr[2] [ arr[2]>10 ] )
print(arr[2]>10)

[13  9  9  7]
[13]
[ True False False False]


### 5.ndarray的运算

In [37]:
# 算数的运算
#一维数组
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** 2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 2 3]
[1 4 9]


In [38]:
c = [1,2,3]
d = [4,5,6]
print(a + b)
for i in range(len(c)):
    d[i] = d[i] + c[i]
print(d)

[5 7 9]
[5, 7, 9]


In [39]:
# 算数的运算
#二维数组
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6]])
print(a + b)
print(a + 3)
print(a * b)
print(a * 3)

[[5 7 9]
 [5 7 9]]
[[4 5 6]
 [4 5 6]]
[[ 4 10 18]
 [ 4 10 18]]
[[3 6 9]
 [3 6 9]]


In [40]:
#广播机制: 1.获取维度、形状 2.是否可以广播
#(满足其一即可)可以广播：1.两个数组在该维度的大小相同
#        2.其中一方在该维度大小为 1，会被扩展
#        3.缺失的维度视为 1
a = np.array([1,2,3])  #1*3
print(a.shape)
b = np.array([[4],[5],[6]])  #3*1
print(b.shape)
print(a+b)

(3,)
(3, 1)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [41]:
image = np.random.randint(0, 255, (224, 224, 3)) ## 224行，224列，3个通道（RGB）
print(image)

[[[ 63  61  22]
  [ 57   1 128]
  [ 60 209   8]
  ...
  [ 78  33  27]
  [179  77  30]
  [171 174   9]]

 [[ 67   3 195]
  [ 54  97 191]
  [227  80  28]
  ...
  [114 214 254]
  [ 58  88 127]
  [ 51 150  10]]

 [[107  31 244]
  [  9 103 134]
  [158  67 146]
  ...
  [113 221 176]
  [110  13  19]
  [143  97 169]]

 ...

 [[ 74 221 163]
  [249 241 253]
  [218 152 254]
  ...
  [ 75 167  92]
  [240  39  82]
  [ 91 115 197]]

 [[220 111 153]
  [144  45 179]
  [  1 121  33]
  ...
  [ 23 198 167]
  [162 229   0]
  [ 84  56 218]]

 [[173  94  64]
  [ 52 214 117]
  [212 182   1]
  ...
  [ 72  90 135]
  [  8 177 105]
  [ 79 209  31]]]


In [42]:
#矩阵运算
a = np.array([[1,2,3],[1,2,3]])  #2*3
b = np.array([[4],[5],[6]])   #3*1
print(a @ b)

[[32]
 [32]]


2.统计函数

求和，平均数，标准差，中位数，方差

查找最大值，最小值

计算分位数，累计和，累计差

In [43]:
arr = np.random.randint(0,10,8)
print(arr)

[6 1 0 5 8 2 9 1]


In [44]:
#求和
print(np.sum(arr))
print(np.sum([1,2,3]))

32
6


In [45]:
#平均值
print(np.mean([1,2,3]))

2.0


In [46]:
#中位数
print(np.median([3,5,4,2,6])) #从小到大排列后，奇数个 取中间数，偶数个 取中间两数平均值
print(np.median([3,5,4,2]))

4.0
3.5


In [47]:
#方差，标准差用来检验系统稳定性，越小越稳定
#方差
#mean=2
#var=( (1-2)^2 + (2-2)^2 + (3-2)^2 ) / 3
print(np.var([1,2,3]))
a=np.var([1,2,3])
#标准差
#std=sqrt(var)
print(np.std([1,2,3]))
print(np.sqrt(a))

0.6666666666666666
0.816496580927726
0.816496580927726


In [48]:
print(np.max([1,2,3]),np.argmax([1,2,3])) #找值，找索引值（位置）
print(np.min([1,2,3]), np.argmin([1,2,3]))

3 2
1 0


In [49]:
#分位数
arr = np.random.randint(0,100,5)
print(arr)

[64 19 18 23  1]


|------------------|

 37  50  69  71  77

 中位数：69

 分位数：看这组数中所在位置（0%-100%）的对应数值。

5个数分了4段，找到该百分比所对应的段位，用这一段的数值范围×这个数在该段的百分比+该段起始值


In [50]:
print(np.median(arr))
print(np.percentile(arr,50)) #50%——>中位数
print(np.percentile(arr,20))
#4*0.2=0.8 -->第一段  ；  （50-37）*0.8=10.4   ； 10.4+37=47.4
print(np.percentile(arr,80))
#4*0.8=3.2 -->第4段  ；  （77-71）*0.2=1.2   ； 1.2+71=72.2
print(np.percentile(arr,60))
#4*0.6=2.4 -->第3段  ；  （71-69）*0.4=0.8   ； 0.8+69=69.8

19.0
19.0
14.600000000000001
31.200000000000006
20.6


In [51]:
#累计和
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
#累计积
print(np.prod(arr))
print(np.cumprod(arr))

6
[1 3 6]
6
[1 2 6]


比较函数

判断、>，<，=

逻辑与或非

检查数组中是否有一个是True ,是否所有都是True ,自定义条件

In [52]:
#是否大于
print(np.greater([1,2,3,5,6,7],5))
#是否小于
print(np.less([1,2,3,5,6,7],5))
#是否等于
print(np.equal([1,2,3,5,6,7],5))
print(np.equal([1,2,3,5,6,7],[2,2,2,2,2,2]))

[False False False False  True  True]
[ True  True  True False False False]
[False False False  True False False]
[False  True False False False False]


In [53]:
print(np.logical_and([1,2,0],[0,1,0]))
print(np.logical_or([1,2,0],[0,1,0]))
print(np.logical_not([1,2,0]))

[False  True False]
[ True  True False]
[False False  True]


In [54]:
print(np.any([1,2,0]))
print(np.any([0,0,0]))
print(np.all([2,0,0]))
print(np.all([1,1,1]))

True
False
False
True


In [55]:
#自定义条件
#print(np.where(条件，符合条件，不符合条件))
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))
print(np.where(arr>3,1,0))

[1 2 0 0 0]
[0 0 0 1 1]


In [56]:
score = np.random.randint(50,100,15)
print(score)

[68 87 82 67 74 87 57 63 55 81 57 70 60 57 92]


In [57]:
#嵌套
print(np.where(
    score<60,'D',np.where(
        score<75,'C',np.where(
            score<85,'B','A'
        )
    )
))

['C' 'A' 'B' 'C' 'C' 'A' 'D' 'C' 'D' 'B' 'D' 'C' 'C' 'D' 'A']


In [58]:
#print(np.select(条件，返回结果，default))
print(np.select([score<60, (score>=60)  & (score<75), (score>=75)  & (score<85), score>=85] ,
                ['D','C' ,'B','A'],
                default='0'))

['C' 'A' 'B' 'C' 'C' 'A' 'D' 'C' 'D' 'B' 'D' 'C' 'C' 'D' 'A']


排序函数`

In [59]:
np.random.seed(1)
arr = np.random.randint(0,100,10)
print(arr)
#不改变arr，只排序
print(np.sort(arr))
print(arr)
#排序后，改变arr
arr.sort()
print(arr)

[37 12 72  9 75  5 79 64 16  1]
[ 1  5  9 12 16 37 64 72 75 79]
[37 12 72  9 75  5 79 64 16  1]
[ 1  5  9 12 16 37 64 72 75 79]


In [60]:
#去重函数
arr = np.array([3,2,2,4,5,6])
print(np.unique(arr))

[2 3 4 5 6]


In [61]:
#数组拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))
print(np.concat((arr1,arr2)))

[5 7 9]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [62]:
#数组的分割
arr = np.array([3,2,2,4,5,6])
print(np.split(arr,3))
print(np.split(arr,[1,3,5]))#索引1前取值，索引3前取值，索引5前取值，剩余元素

[array([3, 2]), array([2, 4]), array([5, 6])]
[array([3]), array([2, 2]), array([4, 5]), array([6])]


In [63]:
#调整数组形状
print(np.reshape(arr,(2,3)))

[[3 2 2]
 [4 5 6]]


## numpy练习题

1---温度数据分析

[28,30,29,31,32,30,29]

In [64]:
#平均气温
import numpy as np
arr = np.array([28,30,29,31,32,30,29])
print('平均气温：','%.3f'%np.mean(arr))
print('最高气温：',np.max(arr))
print('最低气温：',np.min(arr))
print('气温超过30的天数：',len(arr[arr>30]))

a = np.where(arr>30)[0]  # 返回一维数组 [4, 5]
print(f'第{a+1}天超过30')

a = np.argwhere(arr>30)
print(f'第{a+1}天超过30')

a = np.where(arr>30)[0] + 1  # [, 5]
days_str = '、'.join(map(str, a))  # 变成 "4、5"  #map(str, a)：把数组的每个元素转成字符串  #'、'.join(...)：用顿号连接所有字符串
print(f'第{days_str}天超过30')
# 输出：第4、5天超过30

b = np.sum(np.where(arr>30,1,0))
print('气温超过30的天数：',b)

平均气温： 29.857
最高气温： 32
最低气温： 28
气温超过30的天数： 2
第[4 5]天超过30
第[[4]
 [5]]天超过30
第4、5天超过30
气温超过30的天数： 2


2---学生成绩统计

5名学生 单科成绩分别为[85,90,78,92,88]

In [65]:
#平均分，中位数，标准差
score = np.array([85,90,78,92,88])
print('平均分：',np.mean(score))
print('中位数：',np.median(score))
print('标准差：','%.3f'%np.std(score))
#成绩转换为十分制
print(score/10)

平均分： 86.6
中位数： 88.0
标准差： 4.883
[8.5 9.  7.8 9.2 8.8]


3---矩阵运算

A=[[1,2],[3,4]]  B=[[5,6],[7,8]]

In [66]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
#A+B
print(A+B)
#A*B
print(A*B)
#A·B
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


4---随机数据生成

In [67]:
#(3,4)随机整数数组，范围[0，10)
a=np.random.randint(0,10,(3,4))
print(a)

[[7 6 9 2]
 [4 5 2 4]
 [2 4 7 7]]


In [68]:
#计算每列max 每行min
print(np.min(a[0,:]))
print(np.min(a[1,:]))
print(np.min(a[2,:]))
print(np.max(a[:,0]))
print(np.max(a[:,1]))
print(np.max(a[:,2]))
print(np.max(a[:,3]))
print('每行min',np.min(a,axis=1))
print('每列max',np.max(a,axis=0))

2
2
2
7
6
9
7
每行min [2 2 2]
每列max [7 6 9 7]


In [69]:
#将数组中所有奇数换为-1
print(np.where(a%2==1,-1,a))
#布尔索引
a[a%2==1]=-1
print(a)

[[-1  6 -1  2]
 [ 4 -1  2  4]
 [ 2  4 -1 -1]]
[[-1  6 -1  2]
 [ 4 -1  2  4]
 [ 2  4 -1 -1]]


5---数组的变形

In [70]:
arr = np.arange(1,13)
print(arr)
b=np.reshape(arr,(3,4))
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
#计算每行的和
print(b[0,:])
print(np.sum(b[0,:]))

print(np.sum(b,axis=1))
#计算每列的平均值
print(np.mean(b,axis=0))
#将数组展平为一维数组
print(np.reshape(b,(12)))

[1 2 3 4]
10
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


6---布尔索引

In [72]:
arr = np.random.randint(0,20,(5,5))
print(arr)

[[ 9 17  0 13  9]
 [ 9  7  1  0 17]
 [ 8 13 19 15 10]
 [ 8  7  3  6 17]
 [ 3  4 17 11 12]]


In [73]:
print(arr[arr>10])
print(np.where(arr>10,0,arr))

[17 13 17 13 19 15 17 17 11 12]
[[ 9  0  0  0  9]
 [ 9  7  1  0  0]
 [ 8  0  0  0 10]
 [ 8  7  3  6  0]
 [ 3  4  0  0  0]]


7---统计函数应用

In [74]:
arr = np.array([120,135,110,125,130,140])
print('总和：',np.sum(arr))
print('均值：','%.3f'%np.mean(arr))
print('方差：','%.3f'%np.var(arr))
print('最大月份：',np.argmax(arr)+1)
print('最小月份：',np.argmin(arr)+1)

总和： 760
均值： 126.667
方差： 97.222
最大月份： 6
最小月份： 3


8---数组拼接

In [75]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(A+B)
c=np.concatenate((A,B))
print(c)
print(np.reshape(c,(2,3)))

[5 7 9]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


9---唯一值与排序m

In [76]:
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))
u_arr , counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[1 2 3 4]
[2 2 2 1]


In [77]:
arr=np.array([5,7,6,8,8])
print('利润：',arr)

day = np.where(arr==np.max(arr))[0]+1
days_str = '、'.join(map(str, day))
print(f'第{days_str}天利润最高')

a=arr[arr==np.max(arr)]
print('最高利润：',a)
print('最高利润持续天数：',np.sum(np.where(a,1,0)))

利润： [5 7 6 8 8]
第4、5天利润最高
最高利润： [8 8]
最高利润持续天数： 2
